# Generated by Django 4.2.1 on 2023-05-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('type__in', [('CUSTOMER', 'Customer'), ('SELLER', 'Seller'), ('OTHER', 'Other')])), name='accounts_user_type_valid'),
        ),
    ]
