# Generated by Django 4.2.1 on 2023-05-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_accounts_user_type_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_type_valid',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['CUSTOMER', 'SELLER', 'OTHER'])), name='accounts_user_type_valid'),
        ),
    ]
