# Generated by Django 4.2.1 on 2023-05-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="productitem",
            old_name="qty",
            new_name="qty_in_stock",
        ),
        migrations.AddField(
            model_name="productitem",
            name="price",
            field=models.FloatField(default=10.99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcat",
                to="shop.category",
            ),
        ),
    ]
