# Generated by Django 4.2.1 on 2023-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(default='static/no_image.jpg', upload_to=''),
        ),
    ]
