# Generated by Django 4.2.1 on 2023-05-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_address_alter_userprofile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('product_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(choices=[(shop.models.product.ProductSize['M'], 'M'), (shop.models.product.ProductSize['X'], 'X'), (shop.models.product.ProductSize['XL'], 'XL'), (shop.models.product.ProductSize['XLL'], 'XLL')], max_length=20)),
                ('product_color', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('BLACK', 'BLACK'), ('WHITE', 'White')], max_length=20)),
                ('qty', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField()),
                ('delivery_method', models.CharField(choices=[(shop.models.product.DeliveryMethods['PTH'], ''), (shop.models.product.DeliveryMethods['REDX'], 'REDX'), (shop.models.product.DeliveryMethods['FEDX'], 'FedEX'), (shop.models.product.DeliveryMethods['DHL'], 'DHL')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
