# Generated by Django 4.2.1 on 2023-05-11 14:15

from django.db import migrations, models
import shop.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_productitem_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[(shop.models.product.Status['PENDING'], 'Pending'), (shop.models.product.Status['CONFIRMED'], 'Confirmed'), (shop.models.product.Status['DELIVERED'], 'Delivered')], default='Fast', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productorder',
            name='delivery_method',
            field=models.CharField(choices=[(shop.models.product.DeliveryMethods['PTH'], 'Pathao'), (shop.models.product.DeliveryMethods['REDX'], 'REDX'), (shop.models.product.DeliveryMethods['FEDX'], 'FedEX'), (shop.models.product.DeliveryMethods['DHL'], 'DHL')], max_length=20),
        ),
    ]
