# Generated by Django 4.2.1 on 2023-05-25 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_address_address_line2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
