# Generated by Django 4.2.1 on 2023-07-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
    ]
