# Generated by Django 4.2.1 on 2023-05-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_agun_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agun',
        ),
    ]
