# Generated by Django 4.2.1 on 2023-09-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
