# Generated by Django 4.2.1 on 2023-05-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_agun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_item',
        ),
    ]
