# Generated by Django 4.2.1 on 2023-05-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productitem_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('CD', 'Confirmed'), ('DL', 'Delivered')], default='PD', max_length=20),
        ),
    ]
