# Generated by Django 4.2.1 on 2023-11-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_type'),
        ('shop', '0008_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='merchant_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller'),
            preserve_default=False,
        ),
    ]
