# Generated by Django 4.2.1 on 2023-06-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_address_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.PositiveIntegerField(default=700),
            preserve_default=False,
        ),
    ]
