# Generated by Django 4.2.1 on 2023-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../../static/images/default.jpg', upload_to='profile_pic'),
        ),
    ]
