# Generated by Django 4.2.1 on 2023-11-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderitem_merchant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='shop.producttype'),
            preserve_default=False,
        ),
    ]
