# Generated by Django 4.2.1 on 2023-11-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productitem_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_color',
            field=models.CharField(blank=True, choices=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#FF0000', 'Red'), ('#800000', 'Maroon'), ('#DC143C', 'Crimson'), ('#FFFF00', 'Yellow'), ('#008000', 'Green'), ('#00FF00', 'Lime'), ('#000080', 'Navy'), ('#0000FF', 'Blue'), ('#800080', 'Purple'), ('#FFC0CB', 'Pink'), ('#FF1493', 'Deep Pink')], default=None, max_length=20, null=True),
        ),
    ]
