# Generated by Django 4.2.1 on 2023-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='../../static/images/145843.png', upload_to='profile_pic'),
        ),
    ]
