# Generated by Django 4.2.1 on 2023-11-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productitem_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_color',
            field=models.CharField(blank=True, choices=[('White', '#FFFFFF'), ('Black', '#000000'), ('Red', '#FF0000'), ('Maroon', '#800000'), ('Crimson', '#DC143C'), ('Yellow', '#FFFF00'), ('Green', '#008000'), ('Lime', '#00FF00'), ('Navy', '#000080'), ('Blue', '#0000FF'), ('Purple', '#800080'), ('Pink', '#FFC0CB'), ('Deep Pink', '#FF1493')], default=None, max_length=20, null=True),
        ),
    ]
