# Generated by Django 4.2.1 on 2023-11-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_productitem_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_color',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black', 'Black'), ('Red', 'Red'), ('Maroon', 'Maroon'), ('Crimson', 'Crimson'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Lime', 'Lime'), ('Navy', 'Navy'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Deep Pink', 'Deep Pink')], default=None, max_length=20, null=True),
        ),
    ]
