# Generated by Django 4.2.1 on 2023-11-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='title',
            field=models.CharField(default='Test Product', max_length=255),
            preserve_default=False,
        ),
    ]
